# Esta é uma imagem base Ubuntu
FROM ubuntu

# Atualiza a lista de pacotes
RUN apt update

# Instala o curl
RUN apt install curl --yes

# Dockerfile é um arquivo de texto que contém um conjunto de instruções para o Docker criar uma imagem personalizada. 
# Ele especifica o que deve ser feito durante o processo de construção da imagem, como a instalação de pacotes, configuração do sistema, entre outras coisas. 
# As instruções são executadas em sequência, e cada instrução cria uma camada na imagem resultante.

