name: CI

on:
  push:
    branches: [main]
  


  workflow_dispatch:


jobs:

  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 
        uses: actions/setup-node@v4.3.0
        with:
          node-version: 16.15.1

      - name: Install Mocha Test and package
        run: 
          cd DevOps;
          cd material;
          cd conversao-temperatura-2;
          cd src;
          npm install -g mocha;
          npm install

      - name: Execução do Teste
        run: mocha src/test/convert.js
