name: CI

on:
  push:
    branches:
      - main  # Ou a branch de sua preferência
  pull_request:
    branches:
      - main  # Ou a branch de sua preferência

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # Configurar Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Construir a imagem Docker
      - name: Build Docker image
        run: |
          docker build -t my-app .

      # Rodar o container Docker para testar
      - name: Run Docker container
        run: |
          docker run -d -p 8080:8080 --name my-app-container my-app

      # Rodar testes dentro do container (ajuste conforme necessário)
      - name: Run tests inside the container
        run: |
          docker exec my-app-container npm test

      # Parar e remover o container
      - name: Stop and remove container
        run: |
          docker stop my-app-container
          docker rm my-app-container
