name: CI

on:
  push:
    branches: [main]
  


  workflow_dispatch:


jobs:

  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 
        uses: actions/setup-node@v4.3.0
        with:
          node-version: 16.15.1

      - name: Install Mocha Test and package
        run: 
          cd DevOps;
          cd material;
          cd conversao-temperatura-2;
          cd src;
          npm install -g mocha;
          npm install

      - name: Execução do Teste
        run: mocha DevOps/material/conversao-temperatura-2/src/test/convert.js
        
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: eduardopeter91
          password: dckr_pat_hoQvVOHNR4aO80eWPOKMtoXylmk
          

      - name: Construção da Imagem Docker
        uses: docker/build-push-action@v6.15.0
        with:
          context: DevOps/material/conversao-temperatura-2/src
          file: DevOps/material/conversao-temperatura-2/src/Dockerfile
          push: true
          tags: |
            eduardopeter91/conversao-temperatura-2:v1
            eduardopeter91/conversao-temperatura-2:latest


        
